#!/bin/sh
# Generated by `evie-kit setup` — DO NOT EDIT (every setup/upgrade
# run rewrites this file wholesale).
#
# Dependency-free BY DESIGN: this hook diagnoses a missing evie-kit
# toolchain, so it must not invoke that toolchain to do it.
root="${CLAUDE_PROJECT_DIR:-.}"
if [ -f "$root/node_modules/@evie-kit/cli/src/evie-kit.ts" ]; then
  # The toolchain IS here, so the dependency-free rule has done its job
  # and the copies handshake (EVA-94) can run through it: this is the
  # session-start warning that says how stale this repo's copied skills,
  # hooks, and scaffolding are, naming the remedy. Strictly best-effort
  # — no bun on PATH, a failed check, anything at all — because a
  # SessionStart hook that errors is worse than one that stays quiet.
  if command -v bun >/dev/null 2>&1; then
    bun "$root/node_modules/@evie-kit/cli/src/evie-kit.ts" copies check --quiet --hook --target "$root" 2>/dev/null || true
  fi
  exit 0
fi
cat <<'EOF'
[evie-kit] The toolchain is NOT installed in this checkout.

This repo's committed skills and hooks name commands that live in
node_modules/@evie-kit/cli — a machine-local link that git does not
carry and that `bun install` does not create. Until the bootstrap runs,
every `bun node_modules/@evie-kit/cli/src/evie-kit.ts ...`
invocation fails with module-not-found. That is an UN-RUN BOOTSTRAP, not
a broken repo: the instructions are correct, the toolchain is absent.

Fix it from an evie-kit checkout on this machine. The first invocation
is by PATH, because the linked command does not exist yet:

    bun /path/to/evie-kit/packages/cli/src/evie-kit.ts onboard

EVIE-KIT.md in this repo has the full bootstrap — where to clone the
evie-kit checkout from, and who to ask for access.
EOF
exit 0
