sonar.projectKey=semaphile
sonar.projectName=semaphile
sonar.sourceEncoding=UTF-8
sonar.sources=packages
sonar.tests=conformance
sonar.exclusions=**/node_modules/**,**/*.test.*,**/dist/**,**/target/**,**/conformance/fixtures/**,goals/**
sonar.typescript.tsconfigPaths=packages/core/tsconfig.json,packages/redis/tsconfig.json,packages/messaging/tsconfig.json,packages/otel/tsconfig.json
sonar.working.directory=.tmp/sonarqube/work
