sonar.projectKey=semaphile
sonar.projectName=semaphile
sonar.sourceEncoding=UTF-8
sonar.sources=packages,tools
sonar.tests=conformance
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.d.ts,**/._*
sonar.typescript.tsconfigPaths=packages/core/tsconfig.json,packages/redis/tsconfig.json,packages/messaging/tsconfig.json,packages/otel/tsconfig.json
sonar.javascript.lcov.reportPaths=.tmp/coverage/lcov.info
sonar.working.directory=.tmp/sonarqube/work
